tags:
- name: Datebase

paths:
# [PUT] update
  /db/update:
    put:
      tags:
      - Datebase
      summary: inserts key-value under the given namespace, if key exists in namespace value is updated.
      requestBody:
        description: transaction Data
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/trx-value'
      responses:
        200:
          description: 'Transaction successful'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'
# [DELETE] update
    delete:
      tags:
      - Datebase
      summary: Removes a key and its value from the given namespace.
      parameters:
      - name: body
        in: body
        description: transaction Data
        required: true
        schema:
          $ref: '#/definitions/trx-key'
      responses:
        200:
          description: 'Transaction successful'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'
# [POST] select
  /db/select:
    post:
      tags:
      - Datebase
      summary: Selects the given key under the given namespace.
      requestBody:
        description: transaction Data
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/trx-key'
      responses:
        200:
          description: 'Transaction successful'
        400:
          description: 'Bad Request'
        404:
          description: 'Not Found'
        500:
          description: 'Server Error'
# [POST] exists
  /db/exists:
    post:
      tags:
      - Datebase
      summary: Whether a key is present in the target DB.
      requestBody:
        description: transaction Data
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/trx-key'
      responses:
        200:
          description: 'Transaction successful'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'
# [DELETE] empty
  /db/empty:
    delete:
      tags:
      - Datebase
      summary: Removes all key-values under the given namespace.
      requestBody:
        description: transaction Data
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/definitions/trx-namespace'
      responses:
        200:
          description: 'Transaction successful'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# definitions
definitions:
  trx-namespace:
    type: object
    properties:
      namespace:
        type: string
        description: Namespace
  trx-key:
    type: object
    required:
      - key
    properties:
      namespace:
        type: string
        description: Namespace
      key:
        type: string
        description: Key
  trx-value:
    type: object
    required:
      - key
      - value
    properties:
      namespace:
        type: string
        description: Namespace
      key:
        type: string
        description: Key
      value:
        type: object
        description: JSON value

schemes:
  - http
